name: Risk_Management
on:
  workflow_dispatch:
jobs:
  RM_Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
       - name: Prepare 
         run: |
           node -v
           npm config set unsafe-perm true
           npm i -g @sap/cds-dk
           npm install
       - name: unit-test
         run: |
           ls
           echo ">> Runnning the local unit tests"
           npm run-script test:unit
       - name: build
         run: |
           cd tests/mocks
           cds build --production
           mv manifest.yml gen/srv/manifest.yml
