name: Risk_Management
on:
  workflow_dispatch:
jobs:
  RM_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          rm -rf github-action
           git clone https://.:${{ secrets.GITHUB_TOKEN }}@https://github.com/ANUGRAHG/github-action.git
           
           sudo apt-get install nodejs
           sudo apt-get install npm
           
           node -v
