name: Risk_Management
on:
  workflow_dispatch:
jobs:
  RM_Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
       - name: Prepare 
         run: |
           node -v
           npm config set unsafe-perm true
           npm i -g @sap/cds-dk
           npm install
       - name: unit-test
         run: |
           ls
           echo ">> Runnning the local unit tests"
           npm run-script test:unit
       - name: build
         run: |
           cd tests/mocks
           cds build --production
           mv manifest.yml gen/srv/manifest.yml
       - uses: actions/setup-ruby@v1
         with: 
           ruby-version: '2.6'
       - run: |
           ls
           npm install -g mbt
           mbt build -p=cf
       - name: Set up CF CLI
         uses: jvalkeal/setup-cf-cli@v0
         with:
           version: 6.51.0
       - name: Deploy
         run: |
           cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
           cf push -f tests/mocks/gen/srv/manifest.yml
           cf deploy mta_archives/cpapp_1.0.0.mtar
         env:
           CF_API: ${{ secrets.CF_API }}
           CF_ORG: ${{ secrets.CF_ORG }}
           CF_SPACE: ${{ secrets.CF_SPACE }}
           CF_USERNAME: ${{ secrets.CF_USERNAME }}
           CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
