name: Risk_Management
on:
  workflow_dispatch:
jobs:
  RM_Pipeline:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
       - name: Prepare 
         run: |
           node -v
           npm config set unsafe-perm true
           npm i -g @sap/cds-dk
           npm install
       - name: unit-test
         run: |
           ls
           echo ">> Runnning the local unit tests"
           npm run-script test:unit
       - name: build
         run: |
           cd tests/mocks
           cds build --production
           mv manifest.yml gen/srv/manifest.yml
           cd ../..
           
       - name: Update package.json with mock destination
         uses: jossef/action-set-json-field@v1
         with:
           file: package.json
           field: cds.requires.API_BUSINESS_PARTNER["[production]"].credentials.destination
           value: cap-api098-mock

       - run: |
           ls
           npm install -g mbt
           mbt build -p=cf
       - name: Set up CF CLI
         uses: jvalkeal/setup-cf-cli@v0
         with:
           version: 6.51.0
           
       - name: Deploy
         run: |
           echo 'y' | cf install-plugin multiapps
           cf login -a $CF_API -u $CF_USERNAME -o $CF_ORG -s $CF_SPACE -p $CF_PASSWORD
           cf push -f tests/mocks/gen/srv/manifest.yml
           cf deploy mta_archives/cpapp_1.0.0.mtar
         env:
           CF_API: ${{ secrets.CF_API }}
           CF_ORG: ${{ secrets.CF_ORG }}
           CF_SPACE: ${{ secrets.CF_SPACE }}
           CF_USERNAME: ${{ secrets.CF_USERNAME }}
           CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
       - name: prepare for integration-test
         run: |
           appId=`cf app cpapp-srv --guid`
           `cf curl /v2/apps/$appId/env > tests/appEnv.json`
           chmod 777 tests/appEnv.json
           cat tests/appEnv.json
           
       - name: Update appEnv.json pusername
         uses: jossef/action-set-json-field@v1
         with:
           file: tests/appEnv.json
           field: pusername
           value: ${{ secrets.CF_USERNAME }}
           
       - name: Update appEnv.json puserpwd
         uses: jossef/action-set-json-field@v1
         with:
           file: tests/appEnv.json
           field: puserpwd
           value: ${{ secrets.CF_PASSWORD }} 
           
       - name: run integration-test
         run: |
           cat tests/appEnv.json
           npm install --only=dev
           npm run-script test:integration
           
       - name: Undeploy
         run: |
           echo 'y' | cf undeploy cpapp
           echo 'y' | cf delete-service cpapp-db
           echo 'y' | cf delete cpapp-srv-mocks
