name: Ruby_installer
on:
  workflow_dispatch:
jobs:
  RM_Pipeline:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
     #  - run: |
    #      sudo apt-get install rubygems
       - uses: ruby/setup-ruby@v1
         with:
          ruby-version: 2.6
          bundler-cache: true
        # env: 
         #   --env-file: ~/.env
#          ImageOS: ubuntu20
